### ISSUE TITLE
Email notification function

### ISSUE THREAD

**Issue by kaifanzhu** [uoForms/CCM#3] opened 2015-11-30 00:43 UTC
Needs email notification function like the old francine app, which I guess the old one can do that.
Suggest ask Katherine.

**Comment by hannhow** [comment] 2016-01-23 22:08
The root cause is the name of rule engine that DAO seeks for changes based on the app, but the only instance of rule engine we have right now is named Pregapp***. Therefore any app whose name is not Pregapp cannot trigger that rule engine.
Should hard code the name of rule engine in DAO to make it adaptive to each app.

**Comment by hannhow** [comment] 2016-02-04 20:44
Please have it tested to see if it works or not.

**Comment by Sunerbones** [comment] 2016-02-04 22:07
Retesting starts as of Feb. 4th. Akosua and Panhua are both subscribing emails from today.

**Comment by Sunerbones** [comment] 2016-02-14 05:40
There is no notification email received from my side and Akosua side since last week. Need to re-look at this issue again.

**Comment by hannhow** [comment] 2016-02-19 19:38
Changes made to the server. All subscribers should receive weekly email on Feb 20th 2016. Please be advised.

**Comment by Sunerbones** [comment] 2016-02-21 01:35
Received an e-mail of week 35 for the first time from my side today. It should be the first week and please check.

**Comment by beneze** [comment] 2016-02-28 22:23
The issue is that the trigger for the notification was coming from an html page that needed to load some JavaScript that would then call the REST API from quickforms. The problem with this, is that loading the JavaScript requires a web browser and that is seen as a script violation for a windows task.

The solution was to call the REST API for pregapp notification directly with a tiny payload. See the attached C# loader - [LoadPregapp.txt](https://github.com/uoForms/CCM/files/150160/LoadPregapp.txt)

The trigger is a SQL Server job running on the quickforms3.eecs.uottawa.ca.

**Comment by hannhow** [comment] 2016-02-29 19:15
Please have it retested. Thanks.

**Comment by beneze** [comment] 2016-02-29 19:18
Do you have data for every day of the week?

**Comment by hannhow** [comment] 2016-02-29 19:22
No... I assigned this ticket to Panhua. He will have it retested.

**Comment by beneze** [comment] 2016-02-29 19:26
Ok. Great!

**Comment by Sunerbones** [comment] 2016-02-29 19:53
I have subscribed using my 2 e-mails and put Monday and Tuesday as different due dates respectively. Will keep an eye on it.

**Comment by hannhow** [comment] 2016-03-01 20:11
The log shows that 1 email has been sent to you today. @Sunerbones 

From: <autoreplypregapp@gmail.com>
Date: Mar 1, 2016 4:33 AM
Subject: Daily notification summary
To: <eze.ben@gmail.com>, <veena.chhattani@gmail.com>
Cc: 

1 subscriber emails have been sent! 

Email sent for user:panhuazhu26@hotmail.com, key:29, current week:31

**Closed** 2016-03-02 04:40 UTC
Labels: High
